### ISSUE TITLE
Combine the raw data and the dictionary into one dataset

### ISSUE THREAD

**Issue by Anna-Pon** [Anna-Pon/Model-Risk#7]
**Задачи**
- Натела
- [x] OFZ AD 
- Марина 
- [x] OFZ PD (Marina)

- Тёма 
- [x] Скрипт
- [x] Металлодобыча (недостаточно бумаг)
- [x] Нефтянка (недостаточно бумаг)
- [x] Электроэнергетика (недостаточно бумаг)
- [x] Транспорт
- [x] Недвижимость
- [x] Телекоммуникации
- [x] Потребительский сектор
- [x] Финансы
- [x] All sectors

**Comment by natela-proger** [comment]
Воскресенье 10/05/2020:
На данный момент были составлены таблицы по всем видам ОФЗ с фиксированным купоном. Ожидаем от сокомандников словари по облигациям первого эшелона, по мере появлениям будем дополнять прогресс

**Comment by argusak** [comment]
Скрипт дописан, объединены все секторы
